name: Self Hosted Demo

on:
  push:

jobs:

  hello:

    runs-on: self-hosted

    steps:

      - name: Hostname
        run: hostname

      - name: Current User
        run: whoami

      - name: Present Directory
        run: pwd
